### ISSUE TITLE
Image file .img

### ISSUE THREAD

**Issue by mehrfeuer** [martim01/pam#10]
Hi,
the documentation pam.html says that there is an image file with preinstalled pam available, but I'm unable to find a link. Where can I download this image?
Thanks a lot,
Dennis

**Comment by martim01** [comment]
Hi Dennis,
I had intended to do this but not got round to it - so thanks for reminding me.
I've just created a new GitHub Release and included a link to the associated image file. 
I shall try to keep doing this for any major changes to the system.
Matt
