### ISSUE TITLE
Session Info / UTC vs TAI

### ISSUE THREAD

**Issue by Gemini2350** [martim01/pam#101]
In The Session Info - Active Subsessions the Nework Latency and Playback Latency is not shown correct when using PTP with the actual TimeofDay.
It shows -37096005us which is nearly exactly 37s.
Time Setting of PAM is PTP.

I think the PAM extracts UTC from the PTP, and the Audio Devices are on TAI (which difference is 37s Today). 

Thanks for all the amazing work!

**Comment by martim01** [comment]
I've added an option on the Time settings page where the user can decide whether to "Sync To UTC" or "Sync To TAI". The first will add (currently) 37s to the synced time before setting the clock. The second will not.

**Comment by Gemini2350** [comment]
Great. Thank you!
