### ISSUE TITLE
PTPmonkey part

### ISSUE THREAD

**Issue by zabaluyev** [martim01/pam#106]
I just start to try using the software, and it is not clear what the PTPmonkey window does. I connected my rpi to the network with the ptp2 clock, and the rpi window shows nothing, while I can see 2 ptpv2 clock generators with the PTPhoundtracker. Maybe I missed something while I made cmake. If you have more details on the ptp and AES67 and NMOS parts of your software, I’d be happy to dig in. Thank you

**Comment by martim01** [comment]
Hi - how do you have you ptp generators setup? At the moment the PTP Monkey plugin will only display generators in multicast mode. I am working on getting unicast and hybrid modes working, but have not completed the code yet.

**Comment by martim01** [comment]
Actually having looked through all the code the PTP bits were only ever going to work when the domain was set to 0. Hopefully will be a new release soon that fixes this and adds some more new features

**Comment by zabaluyev** [comment]
Thank you.
