### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by hackityourselfman** [martim01/pam#108]
Restgoose is not compiled but fails for mutple errors. First error is:
<img width="696" alt="Screenshot 2023-08-11 130202" src="https://github.com/martim01/pam/assets/80944422/1f33efec-0cae-41c3-b344-54507a535068">

**Comment by martim01** [comment]
Agreed - this was due to a misconfiguration in a CMake file pulling the wrong Git branch of Restgoose.
I've done some merging and editing and checked that I the project compiles on a vanilla Docker container and on my usual build machine.

**Comment by hackityourselfman** [comment]
Thanks for checking it out martim. Did you make this fix available yet?

**Comment by martim01** [comment]
Yep - the latest commit should have fixed the issues. I've just done a pull and build from this and it works for me

**Comment by zabaluyev** [comment]
Hello. I was trying to compile it today on the Rpi4 with exit with errors on compiling of Restgoose.

**Comment by martim01** [comment]
I've just updated the repository and it builds okay on my system.
If you have issues I would try deleting the restgoose directory from your pi and make sure your CMake cache is clean.
There was/is an issue with the incorrect restgoose branch being checked out of GitHub
