### ISSUE TITLE
Mouse not showing up on release 2023-08-03

### ISSUE THREAD

**Issue by elraval** [martim01/pam#116]
Hi Martin. Thank you for building PAM.

I don't have a touchscreen and rely on mouse to click. On the latest release mouse cursor is invisible...

Thank you in advance for any guidance.

Diogo

**Comment by martim01** [comment]
You can get the cursor back by editing /home/pam/.bash_profile

remove -nocursor

**Comment by elraval** [comment]
Thanks. That dit the trick. Cheers.
