### ISSUE TITLE
soundcard

### ISSUE THREAD

**Issue by dewiweb** [martim01/pam#12]
Is there a solution to use the onboard audio out (mini-jack) in place of a specific pi-Hat?(or maybe also an usb sound card)

**Comment by martim01** [comment]
If you are building/installing the code yourself then the on board audio out and any compatible usb sound card should be available. PAM uses portaudio which itself uses asio, so any asio compatible in/out should be discovered.

If you are using the prebuilt image then the mini-jack output has been disabled. You need to edit /boot/config.txt to reenable it.

**Comment by dewiweb** [comment]
It could be nice to have the ability to control output volume from pam interface.
(I'm using alsamixer for now but I've to alt+tab between pam and terminal to adjust it....)

**Comment by martim01** [comment]
Latest version allows gain control of outgoing audio if using Soundcard as output
