### ISSUE TITLE
pam user password in prebuilt image

### ISSUE THREAD

**Issue by dewiweb** [martim01/pam#13]
Hello Martin,
What's the password for pam user in prebuilt image.
I'm looking for edit /boot/config.txt file...

**Comment by martim01** [comment]
I think in order to edit /boot/config.txt you'll need super user rights which the pam user deliberately doesn't.
Try 
`su pi `
with password **raspberry**

**Comment by dewiweb** [comment]
Thanks for reply,
It works !

**Comment by Gemini2350** [comment]
Same problem here with the newest Image. But with 
"su pi"  and password raspberry i get 
"su: Authentication failure"
Can you help me? love your tool but i also need to turn the screen ;)

**Comment by martim01** [comment]
Sorry - looks like I changed the password between releases.
The password for  user **pam** is **3045bh** but the user is quite locked down.
The password for user **pi** which allows sudo is **vuByqU43cdRSCHkp**

**Comment by Fischmaster3000** [comment]
did you change the password again? can't login into the latest prebuild image :(

**Comment by martim01** [comment]
Did you not get the setup application when you first booted the new image? This should give you the opportunity to set the password to what you want.

It's possible that the new image has the default password of "raspberry" - the idea being you'd change it with the setup app.

Can you let me know whether the setup application started, and if "raspberry" works. If not then I'll burn a copy of the image for myself and workout what I set the password to.
________________________________
