### ISSUE TITLE
Assertion failed with multiple source pages

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#17]
- Import AoIP configuration with more than one page of AES67 streams
- Open "Audio Monitor Source" page
- Press the next page button
Expected behaviour: Next page of streams shown.
Actual behaviour: Three consecutive assertion failed errors:

```
../src/gtk/pen.cpp(234): assert "IsOk()" failed in GetColour(): invalid pen
../src/gtk/brush.cpp(113): assert "IsOk()" failed in GetColour(): invalid brush
../src/gtk/colour.cpp(241): assert "IsOk()" failed in GetColor(): invalid colour
```

**Comment by martim01** [comment]
Fixed
