### ISSUE TITLE
"Reset" button obscures other screen content

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#19]
There is a blue "Reset" button that is often at the top right-centre of the screen but inexplicably occasionally at the bottom of the screen. The button obscures some content, e.g. Lissajou screen has some text that seems to sit below the button ("Auto ...x inf"). Maybe this is because there is no AES input. Note that even when Audio Monitoring Source is Disabled, this message appears on screen.

**Comment by martim01** [comment]
Shrunk the dialog down to only the button.
Changed the logic so the button does not show if the Audio Monitoring Source is disabled
