### ISSUE TITLE
PAM crashes - 8 channel AoIP

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#22]
Select 8 channel AoIP source.
Select a different source.
PAM crashes.
Any further attempt to select another source will crash PAM, even after restart. Deleting the currently selected 8 channel source and selecting another source initially crashes the PAM but subsequent attempt succeeds.
AoIP discovery also sometimes leads to crash which may be related.

**Comment by martim01** [comment]
This was due to not reseting the size of the vector of monitoring buttons when the number of channels changed (in the anglemeter and levelmeter plugin). Should now be fixed
