### ISSUE TITLE
Generators do not feed (analogue) output

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#24]
- Configure RPi with builtin audio (dtparam=audio=on in /boot/config.txt).
- Select builtin soundcard analogue output as Output Device
- Select Generator (of Sequence of Noise) as Output Source
Expected behaviour: Generator feeds analogue output.
Actual behaviour: Analogue output is silence.

Selecting Output Source as "Input" and selecting an input does produce audio at analogue output.

**Comment by martim01** [comment]
The problem here was on changing to the generator the output buffer was cleared which meant that the code asking for more generated samples was never called.
Added a line to make sure when changed to a generator we always generate some audio to start off the process
