### ISSUE TITLE
Unresponsive interface even after reboot

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#26]
The device can get into a state where the GUI is unresponsive to touch. This may be related to issue #22. When in this state a reboot returns to same, unresponsive state. The example I saw was the Meter Screen shown. This was fixed by removing network cable.

It may be advantageous to provide a mechanism for starting up in a known working (default) state, e.g. pressing a GUI button during startup.

**Comment by martim01** [comment]
I've added an engineering menu that appears only on rebooting the unit. This gives the ability to reset the unit to a working state
