### ISSUE TITLE
Some screen selection buttons are lowercase

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#29]
The "waveform" and "ptp" screen selection buttons are lowercase. Other buttons have first letter of each work capitalised and TLAs in upper case.

**Comment by martim01** [comment]
Screen selection buttons are taken from the name of the plugin shared library. Could possibly change it so that they are uppercase first letter of each word, but could be a bit tricky

**Comment by martim01** [comment]
Actually the above was incorrect. I've changed the PTP screen selection to be correct. The waveform plugin is a "test" plugin so won't be changed for now
