### ISSUE TITLE
Feature request: Display AES67 streams in non-alphabetical order

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#37]
It is now possible to import AES67 stream configuration from USB. It would be advantageous to be able to define the order of display from the order within the file. It seems that the current implementation orders alphabetically. It may be further advantageous to offer switch between configured / discovered order and alphabetic order.

**Comment by martim01** [comment]
Added abilty to display AES67 streams by
user defined index order (or discovered order if using discovery)
alphabetical
via tags
