### ISSUE TITLE
Display locks up (when switching meter)

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#38]
On several occasion the GUI has locked up and become unresponsive. On most recent occasion this was when switching Screens from FFT to R128. Switching to terminal I can see that pam2 process is taking 123% CPU. Killing pam2 process does not relaunch PAM GUI. (Killing lightdm restarts UI with login prompt.)

After reboot I was able to reproduce the issue. Selecting R128 (from any Screen) seems to lock up the display (if AES67 source selected).

**Comment by martim01** [comment]
Repeat of issue #33
