### ISSUE TITLE
Please could you add a licence

### ISSUE THREAD

**Issue by peternewman** [martim01/pam#4]
Hi Matthew,

I've been trying to add your software to the EBU's awesome broadcasting list, because well it's awesome, however they'd like it to have a defined open source licence ( https://github.com/ebu/awesome-broadcasting/issues/135 ). Would you be able to choose one please and add it to your repository. There's some info and guidance here:
https://help.github.com/en/articles/licensing-a-repository

Thanks

**Comment by martim01** [comment]
Hi Peter,
Glad you like the software, I've added a licence so that it can be added to the EBU list.
Thanka

**Comment by peternewman** [comment]
Great, thanks very much Matthew.
