### ISSUE TITLE
USB flash sometimes not mounting

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#42]
Occasionally the PAM does not recognise a USB memory device. Sometimes it displays multiple copies of files, like it may have mounted the device twice.

It is plausible that automount is running and mounting the media and PAM is manually mounting it. It may be that if one does so before the other it may block the second mount and it may be that if the mount occurs in opposite order then the device may get mounted twice.

**Comment by martim01** [comment]
Think this is due to the pcmanfm application sometimes automounting the USB before PAM has the chance. I've turned off the auto-mount in the latest release image and updated the wiki with instructions on how to do this.
