### ISSUE TITLE
cmake rule fails - openssl error

### ISSUE THREAD

**Issue by riban-bw** [martim01/pam#46]
Building using cmake instructions in README fails with error:

```
fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
``` 
This can be resolved by adding libssl-dev to the list of packages to install.

**Comment by martim01** [comment]
Live555 added open ssl support in their last release. PAM does not need to use it so I've added the compiler defintion NO_OPENSSL to the CMakeLists

**Comment by riban-bw** [comment]
You could also add libssl-dev to the list of dependant packages in the README.
