### ISSUE TITLE
PTP Master vs GrandMaster

### ISSUE THREAD

**Issue by Gemini2350** [martim01/pam#54]
In PTP Monkey there is a minor bug in Decoding the PTP Grandmaster clock.
In my Network there is a PTP Boundary Clock, so ClockIdentity and GrandmasterClockIdentity is not the same (see attached Announce Message).
In PTP Monkey it shows me the clockidentity and not the grandmasterclockidentity (nicest would be to see both). In the Session Info Screen it shows me red in the Session Info Sync ID, because in the SDP file there is the grandmasterclock.
I hope you get what i mean ;) 
Thanks for your really amazing work

 
Announce Message:
Precision Time Protocol (IEEE1588)
    0000 .... = transportSpecific: 0x0
    .... 1011 = messageId: Announce Message (0xb)
    0000 .... = Reserved: 0
    .... 0010 = versionPTP: 2
    messageLength: 64
    subdomainNumber: 0
    Reserved: 0
    flags: 0x0008
    correction: 0.000000 nanoseconds
    Reserved: 0
    **ClockIdentity: 0x001c73ffffc59ec5**
    SourcePortID: 11
    sequenceId: 214
    control: Other Message (5)
    logMessagePeriod: 0
    originTimestamp (seconds): 0
    originTimestamp (nanoseconds): 0
    originCurrentUTCOffset: 37
    priority1: 11
    grandmasterClockClass: 248
    grandmasterClockAccuracy: Accuracy Unknown (0xfe)
    grandmasterClockVariance: 65535
    priority2: 66
    **grandmasterClockIdentity: 0x000b72fffe058bae**
    localStepsRemoved: 1
    TimeSource: INTERNAL_OSCILLATOR (0xa0)

SDP File:
v=0
o=- 3 0 IN IP4 192.168.96.56
s=AnubisA
c=IN IP4 239.69.96.56/15
t=0 0
a=clock-domain:PTPv2 0
m=audio 5004 RTP/AVP 98
c=IN IP4 239.69.96.56/15
a=rtpmap:98 L24/48000/2
a=sync-time:0
a=framecount:48
a=ptime:1
a=mediaclk:direct=0
**a=ts-refclk:ptp=IEEE1588-2008:00-0B-72-FF-FE-05-8B-AE:0**
a=recvonly

**Comment by martim01** [comment]
Latest version of PAM and PtpMonkey distinguishes between the GrandMaster and the clock sending Sync messages etc to take in account boundary clocks
