### ISSUE TITLE
Error: Unable to initialize GTK+, is DISPLAY set properly?

### ISSUE THREAD

**Issue by SimpelMe** [martim01/pam#57]
Hi.
Building at `cmake --build .` failed on my raspberry pi: 'asio.hpp missing'.
So I copied last release __1.0.1409.7820__ .

Then I
* installed `sudo apt-get install libwxgtk3.0-dev portaudio19-dev libsndfile1-dev libsamplerate0-dev libavahi-client-dev libcurl4-openssl-dev libmicrohttpd-dev`
* copied the executable `pam2` to `/usr/local/bin`
* and content of `lib` to `/usr/local/lib/pam2`
* created ` /etc/ld.so.conf.d/pam2.conf` with `/usr/local/lib/pam2`
* did `sudo ldconfig`
* created a directory called `pam` in my home directory
* copied the contents of the `documents` directory to the `pam` directory

Running `pam2` calles __Error: Unable to initialize GTK+, is DISPLAY set properly?__

This is my pi:
```
- Original Installation
Raspberry Pi reference 2020-02-13
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 5f884374b6ac6e155330c58caa1fb7249b8badf1, stage4
- Current OS
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
- Kernel
5.4.72-v7+
- Model
Raspberry Pi 3 Model B Rev 1.2
- Firmware
Oct 22 2020 14:06:02 
Copyright (c) 2012 Broadcom
version 74e754ff8947c58d2773253f77f6f68a303188f8 (clean) (release) (start)
```
Do you have a suggestion for me?
Regards, Simpel

**Comment by martim01** [comment]
Hi,
Apologies that CMake build appears to be broken. I'll look in to that.

In terms of the error you are seeing. I see this if I try to run the application as root ( if  I type **sudo pam2** then I get this error). I don't see it otherwise.

I assume attempting to run other GUI applications from the command line run okay?
