### ISSUE TITLE
asio.hpp missing from sapserver/src/parser.cpp

### ISSUE THREAD

**Issue by ds1k99** [martim01/pam#59]
parser.cpp references asio.hpp but is not included within the git tree. Can you offer guidance on this? Is it a boost library that is required?

[ 40%] Building CXX object pambase/CMakeFiles/pambase.dir/__/external/sapserver/src/parser.cpp.o
/home/dave/git/pam/external/sapserver/src/parser.cpp:5:10: fatal error: asio.hpp: No such file or directory
    5 | #include "asio.hpp"
      |          ^~~~~~~~~~
compilation terminated.

**Comment by martim01** [comment]
Hi,
Asio is included as a Git submodule so you should be able to pull it using


git submodule update --init --recursive


Or you can clone the repository https://github.com/chriskohlhoff/asio

It's the non-boost version of Asio


-------- Original message --------
From: ds1k99 ***@***.***>
Date: 29/06/2021 21:06 (GMT+00:00)
To: martim01/pam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [martim01/pam] asio.hpp missing from sapserver/src/parser.cpp (#59)


parser.cpp references asio.hpp but is not included within the git tree. Can you offer guidance on this? Is it a boost library that is required?

[ 40%] Building CXX object pambase/CMakeFiles/pambase.dir/__/external/sapserver/src/parser.cpp.o
/home/dave/git/pam/external/sapserver/src/parser.cpp:5:10: fatal error: asio.hpp: No such file or directory
5 | #include "asio.hpp"
| ^~~~~~~~~~
compilation terminated.

**Comment by ds1k99** [comment]
Marvellous, that's cleared it up thank you.

Forgive my naivety, but I am also missing log.h from the spectogram plugin. your above advise hasn't yielded anything this time. Any advise on this one?

[ 87%] Building CXX object plugins/spectogram/CMakeFiles/spectogram.dir/spectogrammeter.cpp.o
/home/dave/git/pam/plugins/spectogram/spectogrammeter.cpp:10:10: fatal error: log.h: No such file or directory
   10 | #include "log.h"

**Comment by martim01** [comment]
Sorry - that's an error on my part. The include directory was missing from CMakeLists.txt for the Spectogram plugin. If you do a pull on the repository it should now be there.

________________________________
