### ISSUE TITLE
compilation crash "undefined reference to 'pml::Log(pml::enumLevel)'

### ISSUE THREAD

**Issue by dewiweb** [martim01/pam#60]
Trying to compile on rpi3 (rpi os -debian buster) with ptpmonkey and nmos support:
crash at 92%:
"Linking CXX executable ../../bin/pam2
/usr/bin/ld: ../lib/libpambase.so: undefined reference to 'pml::Log(pml::enumLevel)'
collect2: error: ld returned 1 exit status
make[2]: *** [pam2/CMakeFiles/pam2.dir/build.make:667: ../bin/pam2] Error 1
make[1]: *** [CMakeFiles/Makefile2:1593: pam2/CMakeFiles/pam2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2"

**Comment by martim01** [comment]
I've just merged the "newfeatures" branch with the "master" branch and I believe that has fixed this issue. 
I've tested the Codeblocks and CMake build on a vanilla machine and both now build fine.
