### ISSUE TITLE
cmake build error with NMOS

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#63]
**Hello,

I always get the error that the NMOS option was not used.** 

pi@raspberrypi:~/git/pam/build $ cmake .. -DoptionNMOS=ON
-- Configure pambase
/home/pi/git/pam/pambase
Found pml::log
Found pml::dnssd
Found sapserver
Found ptpmonkey
/home/pi/git/pam/pambase
-- Found avahi
-- Found portaudio
-- Found sndfile
-- Configure pamfft
-- Configure pamlevel
-- Found libsamplerate
-- Configure plugin anglemeters
-- Configure plugin aoip
-- Configure plugin channeldelay
-- Configure plugin distortion
-- Configure plugin fft
STATUS,Build Type: Release
-- Configure plugin fftphase
STATUS,Build Type: Release
-- Configure plugin identify
-- Configure plugin levels
-- Configure plugin lineup
-- Configure plugin lissajou
-- Configure plugin LTC
-- Configure plugin LTCGenerator
-- Configure plugin meters
-- Configure plugin peakcount
-- Configure plugin peaklog
-- Configure plugin polarscope
-- Configure plugin r128
-- Configure plugin radar
-- Configure plugin record
-- Configure plugin scope
-- Configure plugin spectogram
-- Configure plugin InputAlign
-- Configure plugin waveform
-- Configure pam2
-- Found libcurl
-- Found avahi-client
-- Found portaudio
unable to set CAP_SETFCAP effective capability: Operation not permitted
-- Configure pamupdatemanager
-- Found libcurl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/git/pam/build

**Another error is that I always get the following error message during the build:(**
short:
[  2%] Built target groupsock
[ 38%] Built target liveMedia
[ 39%] Built target BasicUsageEnvironment
[ 40%] Built target UsageEnvironment
[ 40%] Building CXX object pambase/CMakeFiles/pambase.dir/aes67client.cpp.o
/home/pi/git/pam/pambase/aes67client.cpp: In constructor ‘AES67Client::AES67Client(UsageEnvironment&, unsigned char, const char*, int, const char*)’:
/home/pi/git/pam/pambase/aes67client.cpp:83:53: error: no matching function for call to ‘Groupsock::Groupsock(UsageEnvironment&, in_addr&, int, int)

FULL LOG:
pi@raspberrypi:~/git/pam/build $ cmake --build .
[  2%] Built target groupsock
[ 38%] Built target liveMedia
[ 39%] Built target BasicUsageEnvironment
[ 40%] Built target UsageEnvironment
[ 40%] Building CXX object pambase/CMakeFiles/pambase.dir/aes67client.cpp.o
/home/pi/git/pam/pambase/aes67client.cpp: In constructor ‘AES67Client::AES67Client(UsageEnvironment&, unsigned char, const char*, int, const char*)’:
/home/pi/git/pam/pambase/aes67client.cpp:83:53: error: no matching function for call to ‘Groupsock::Groupsock(UsageEnvironment&, in_addr&, int, int)’
   83 |   fOurSocket = new Groupsock(env, ourAddress, 0, 255);
      |                                                     ^
In file included from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPInterface.hh:30,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPSink.hh:28,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTCP.hh:25,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/MediaSession.hh:52,
                 from /home/pi/git/pam/pambase/aes67client.h:24,
                 from /home/pi/git/pam/pambase/aes67client.cpp:1:
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:83:3: note: candidate: ‘Groupsock::Groupsock(UsageEnvironment&, const sockaddr_storage&, const sockaddr_storage&, Port)’
   83 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |   ^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:83:67: note:   no known conversion for argument 2 from ‘in_addr’ to ‘const sockaddr_storage&’
   83 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:80:3: note: candidate: ‘Groupsock::Groupsock(UsageEnvironment&, const sockaddr_storage&, Port, u_int8_t)’
   80 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |   ^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:80:67: note:   no known conversion for argument 2 from ‘in_addr’ to ‘const sockaddr_storage&’
   80 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:78:7: note: candidate: ‘constexpr Groupsock::Groupsock(const Groupsock&)’
   78 | class Groupsock: public OutputSocket {
      |       ^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:78:7: note:   candidate expects 1 argument, 4 provided
/home/pi/git/pam/pambase/aes67client.cpp:94:47: error: cannot convert ‘Port’ to ‘int’
   94 |   getSourcePort(env, fOurSocket->socketNum(), srcPort);
      |                                               ^~~~~~~
      |                                               |
      |                                               Port
In file included from /home/pi/git/pam/pambase/aes67client.cpp:25:
/home/pi/git/pam/pambase/../external/live/groupsock/include/GroupsockHelper.hh:77:62: note:   initializing argument 3 of ‘Boolean getSourcePort(UsageEnvironment&, int, int, Port&)’
   77 | Boolean getSourcePort(UsageEnvironment& env, int socket, int domain, Port& port);
      |                                                          ~~~~^~~~~~
/home/pi/git/pam/pambase/aes67client.cpp:101:65: error: no matching function for call to ‘Groupsock::Groupsock(UsageEnvironment&, in_addr&, portNumBits&, int)’
  101 |     fOurSocket = new Groupsock(env, ourAddress, fOurPortNum, 255);
      |                                                                 ^
In file included from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPInterface.hh:30,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPSink.hh:28,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTCP.hh:25,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/MediaSession.hh:52,
                 from /home/pi/git/pam/pambase/aes67client.h:24,
                 from /home/pi/git/pam/pambase/aes67client.cpp:1:
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:83:3: note: candidate: ‘Groupsock::Groupsock(UsageEnvironment&, const sockaddr_storage&, const sockaddr_storage&, Port)’
   83 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |   ^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:83:67: note:   no known conversion for argument 2 from ‘in_addr’ to ‘const sockaddr_storage&’
   83 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:80:3: note: candidate: ‘Groupsock::Groupsock(UsageEnvironment&, const sockaddr_storage&, Port, u_int8_t)’
   80 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |   ^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:80:67: note:   no known conversion for argument 2 from ‘in_addr’ to ‘const sockaddr_storage&’
   80 |   Groupsock(UsageEnvironment& env, struct sockaddr_storage const& groupAddr,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:78:7: note: candidate: ‘constexpr Groupsock::Groupsock(const Groupsock&)’
   78 | class Groupsock: public OutputSocket {
      |       ^~~~~~~~~
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:78:7: note:   candidate expects 1 argument, 4 provided
/home/pi/git/pam/pambase/aes67client.cpp: In member function ‘void AES67Client::setProxyServer(unsigned int, portNumBits)’:
/home/pi/git/pam/pambase/aes67client.cpp:162:45: error: cannot convert ‘in_addr’ to ‘const sockaddr_storage&’
  162 |     fOurSocket->changeDestinationParameters(fServerAddress,
      |                                             ^~~~~~~~~~~~~~
      |                                             |
      |                                             in_addr
In file included from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPInterface.hh:30,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPSink.hh:28,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTCP.hh:25,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/MediaSession.hh:52,
                 from /home/pi/git/pam/pambase/aes67client.h:24,
                 from /home/pi/git/pam/pambase/aes67client.cpp:1:
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:93:67: note:   initializing argument 1 of ‘void Groupsock::changeDestinationParameters(const sockaddr_storage&, Port, int, unsigned int)’
   93 |   void changeDestinationParameters(struct sockaddr_storage const& newDestAddr,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/pi/git/pam/pambase/aes67client.cpp: In member function ‘Boolean AES67Client::processURL(const char*)’:
/home/pi/git/pam/pambase/aes67client.cpp:742:42: error: cannot convert ‘in_addr’ to ‘const sockaddr_storage&’
  742 |  fOurSocket->changeDestinationParameters(fServerAddress,
      |                                          ^~~~~~~~~~~~~~
      |                                          |
      |                                          in_addr
In file included from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPInterface.hh:30,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPSink.hh:28,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTCP.hh:25,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/MediaSession.hh:52,
                 from /home/pi/git/pam/pambase/aes67client.h:24,
                 from /home/pi/git/pam/pambase/aes67client.cpp:1:
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:93:67: note:   initializing argument 1 of ‘void Groupsock::changeDestinationParameters(const sockaddr_storage&, Port, int, unsigned int)’
   93 |   void changeDestinationParameters(struct sockaddr_storage const& newDestAddr,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/pi/git/pam/pambase/aes67client.cpp: In static member function ‘static Boolean AES67Client::parseSIPURL(UsageEnvironment&, const char*, NetAddress&, portNumBits&)’:
/home/pi/git/pam/pambase/aes67client.cpp:760:17: warning: unused variable ‘prefix’ [-Wunused-variable]
  760 |     char const* prefix = "sip:";
      |                 ^~~~~~
/home/pi/git/pam/pambase/aes67client.cpp: In static member function ‘static Boolean AES67Client::parseSIPURLUsernamePassword(const char*, char*&, char*&)’:
/home/pi/git/pam/pambase/aes67client.cpp:834:17: warning: unused variable ‘prefix’ [-Wunused-variable]
  834 |     char const* prefix = "sip:";
      |                 ^~~~~~
/home/pi/git/pam/pambase/aes67client.cpp: In member function ‘unsigned int AES67Client::getResponse(char*&, unsigned int)’:
/home/pi/git/pam/pambase/aes67client.cpp:920:25: error: cannot convert ‘sockaddr_in’ to ‘sockaddr_storage&’
  920 |           bytesReadNow, fromAddr);
      |                         ^~~~~~~~
      |                         |
      |                         sockaddr_in
In file included from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPInterface.hh:30,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTPSink.hh:28,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/RTCP.hh:25,
                 from /home/pi/git/pam/pambase/../external/live/liveMedia/include/MediaSession.hh:52,
                 from /home/pi/git/pam/pambase/aes67client.h:24,
                 from /home/pi/git/pam/pambase/aes67client.cpp:1:
/home/pi/git/pam/pambase/../external/live/groupsock/include/Groupsock.hh:142:34: note:   initializing argument 4 of ‘virtual Boolean Groupsock::handleRead(unsigned char*, unsigned int, unsigned int&, sockaddr_storage&)’
  142 |         struct sockaddr_storage& fromAddressAndPort);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
gmake[2]: *** [pambase/CMakeFiles/pambase.dir/build.make:95: pambase/CMakeFiles/pambase.dir/aes67client.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:691: pambase/CMakeFiles/pambase.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2

I use a Raspi 4

**Comment by martim01** [comment]
### Error: "unable to set CAP_SETFCAP effective capability: Operation not permitted"
In order to allow the PTP library access the requisite ports and set the system clock the setcap function is called on the application once it is built. This function must be called as superuser. I've moved the code so hopefully now it is only called if you run `sudo cmake --build . --target install`. The error can be ignored anyway as it shouldn't stop the code from compiling

### Error: no matching function for call to ‘Groupsock::Groupsock(UsageEnvironment&, in_addr&, int, int)
This was an error with the CMakeLists.txt. The file **aes67client.cpp** should no longer be included in the build. I've now deleted them and removed the reference to it in CMakeLists.txt

### NMOS build
I believe the NMOS build should currently work but is not complete. I have been doing a fair amount of rewriting the NMOS library and PAM in order to make them work properly. I'm hoping to merge this work with the main branches shortly.

**Comment by Twister10000** [comment]
The build is now working. 
Unfortunately I still get the following error message when I try to execute this command:
sudo cmake --build . --target install
[  1%] Built target UsageEnvironment
[  3%] Built target groupsock
[ 38%] Built target liveMedia
[ 39%] Built target BasicUsageEnvironment
[ 58%] Built target pambase
[ 60%] Built target pamfft
[ 60%] Built target pamlevel
[ 61%] Built target anglemeters
[ 62%] Built target aoipinfo
[ 63%] Built target channeldelay
[ 64%] Built target distortion
[ 67%] Built target fft
[ 68%] Built target fftphase
[ 69%] Built target identify
[ 70%] Built target levels
[ 71%] Built target lineup
[ 73%] Built target lissajou
[ 74%] Built target LTC
[ 76%] Built target LTCGenerator
[ 78%] Built target meters
[ 79%] Built target peakcount
[ 80%] Built target peaklog
[ 81%] Built target polarscope
[ 83%] Built target r128
[ 84%] Built target radar
[ 85%] Built target record
[ 87%] Built target scope
[ 89%] Built target spectogram
[ 90%] Built target InputAlign
[ 91%] Built target waveform
[ 99%] Built target pam2
[100%] Built target pamupdatemanager
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/pam2/libpambase.so
-- Installing: /usr/local/lib/pam2/libpamfft.so
-- Set runtime path of "/usr/local/lib/pam2/libpamfft.so" to ""
-- Installing: /usr/local/lib/pam2/libpamlevel.so
-- Set runtime path of "/usr/local/lib/pam2/libpamlevel.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libanglemeters.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libanglemeters.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libaoipinfo.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libaoipinfo.so" to ""
-- Installing: /usr/local/lib/pam2/test/libchanneldelay.so
-- Set runtime path of "/usr/local/lib/pam2/test/libchanneldelay.so" to ""
-- Installing: /usr/local/lib/pam2/test/libdistortion.so
-- Set runtime path of "/usr/local/lib/pam2/test/libdistortion.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libfft.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libfft.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libfftphase.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libfftphase.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libidentify.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libidentify.so" to ""
-- Installing: /usr/local/lib/pam2/test/liblevels.so
-- Set runtime path of "/usr/local/lib/pam2/test/liblevels.so" to ""
-- Installing: /usr/local/lib/pam2/test/liblineup.so
-- Set runtime path of "/usr/local/lib/pam2/test/liblineup.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/liblissajou.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/liblissajou.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libLTC.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libLTC.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libLTCGenerator.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libLTCGenerator.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libmeters.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libmeters.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libpeakcount.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libpeakcount.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libpeaklog.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libpeaklog.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libpolarscope.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libpolarscope.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libr128.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libr128.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libradar.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libradar.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/librecord.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/librecord.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libscope.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libscope.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libspectogram.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libspectogram.so" to ""
-- Installing: /usr/local/lib/pam2/test/libInputAlign.so
-- Set runtime path of "/usr/local/lib/pam2/test/libInputAlign.so" to ""
-- Installing: /usr/local/lib/pam2/monitor/libwaveform.so
-- Set runtime path of "/usr/local/lib/pam2/monitor/libwaveform.so" to ""
CMake Error at pam2/cmake_install.cmake:69:
  Parse error.  Function missing ending ")".  End of file reached.
Call Stack (most recent call first):
  cmake_install.cmake:68 (include)


CMake Error at cmake_install.cmake:68 (include):
  include could not find load file:

    /home/pi/pam/build/pam2/cmake_install.cmake


make: *** [Makefile:74: install] Error 1

What else I could find was this error message regarding NMOS support.
cmake .. -DoptionNMOS=ON
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Submodule 'external/dnssd' (https://github.com/martim01/dnssd) registered for path '../external/dnssd'
Submodule 'external/log' (https://github.com/martim01/log) registered for path '../external/log'
Submodule 'external/ptpmonkey' (https://github.com/martim01/ptpmonkey) registered for path '../external/ptpmonkey'
Submodule 'external/sapserver' (https://github.com/martim01/sapserver) registered for path '../external/sapserver'
Cloning into '/home/pi/pam/external/dnssd'...
Cloning into '/home/pi/pam/external/log'...
Cloning into '/home/pi/pam/external/ptpmonkey'...
Cloning into '/home/pi/pam/external/sapserver'...
Submodule path '../external/dnssd': checked out '708b7bf258dbad728c4411e1f7f0fddd830921f8'
Submodule path '../external/log': checked out '2af71aad23496bd121aab39663682b3509a83d5c'
Submodule path '../external/ptpmonkey': checked out '73de69a721cc23931970139d1e0969c441243422'
Submodule 'external/asio' (https://github.com/chriskohlhoff/asio) registered for path '../external/ptpmonkey/external/asio'
Submodule 'external/log' (https://github.com/martim01/log.git) registered for path '../external/ptpmonkey/external/log'
Cloning into '/home/pi/pam/external/ptpmonkey/external/asio'...
Cloning into '/home/pi/pam/external/ptpmonkey/external/log'...
Submodule path '../external/ptpmonkey/external/asio': checked out '0355fc59807198034780c814c799ed353ffe960f'
Submodule path '../external/ptpmonkey/external/log': checked out '08538b849af69b7f5c95759c725410304a9fc67b'
Submodule path '../external/sapserver': checked out '96572b0dc9b4a8d10e385f9ad4bdfd25b06a1ebb'
Submodule 'external/asio' (https://github.com/chriskohlhoff/asio.git) registered for path '../external/sapserver/external/asio'
Cloning into '/home/pi/pam/external/sapserver/external/asio'...
Submodule path '../external/sapserver/external/asio': checked out '0355fc59807198034780c814c799ed353ffe960f'
-- Configure pambase
/home/pi/pam/pambase
Found pml::log
Found pml::dnssd
Found sapserver
Found ptpmonkey
/home/pi/pam/pambase
-- Found wxWidgets: -L/usr/lib/arm-linux-gnueabihf;-pthread;;;-lwx_gtk3u_xrc-3.0;-lwx_gtk3u_html-3.0;-lwx_gtk3u_qa-3.0;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_core-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0;-lwx_baseu-3.0 (found version "3.0.5")
-- Checking for one of the modules 'avahi-client'
-- Found avahi
-- Checking for one of the modules 'portaudio-2.0'
-- Found portaudio
-- Checking for one of the modules 'sndfile'
-- Found sndfile
-- Configure pamfft
-- Configure pamlevel
-- Checking for one of the modules 'samplerate'
-- Found libsamplerate
-- Configure plugin anglemeters
-- Configure plugin aoip
-- Configure plugin channeldelay
-- Configure plugin distortion
-- Configure plugin fft
STATUS,Build Type: Release
-- Configure plugin fftphase
STATUS,Build Type: Release
-- Configure plugin identify
-- Configure plugin levels
-- Configure plugin lineup
-- Configure plugin lissajou
-- Configure plugin LTC
-- Configure plugin LTCGenerator
-- Configure plugin meters
-- Configure plugin peakcount
-- Configure plugin peaklog
-- Configure plugin polarscope
-- Configure plugin r128
-- Configure plugin radar
-- Configure plugin record
-- Configure plugin scope
-- Configure plugin spectogram
-- Configure plugin InputAlign
-- Configure plugin waveform
-- Configure pam2
-- Checking for one of the modules 'libcurl'
-- Found libcurl
-- Found avahi-client
-- Found portaudio
-- Configure pamupdatemanager
-- Found libcurl
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    optionNMOS


-- Build files have been written to: /home/pi/pam/build



I hope you can find a solution for this problem quickly.

**Comment by martim01** [comment]
The CMake build had become a bit of a mess - I think I've fixed it now. I've tested on a vanilla machine and everything now builds without any errors.  I've also automated the adding of the pam2.conf file in to /etc/ld.so.conf.d
