### ISSUE TITLE
PTPMONKEY is not installed as Default settings.

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#64]
Hello 

I have installed the program. However, when I started it, I noticed that the PTPMonkey was not installed.  Do I have to pass a parameter during the Cmake build ? 
<img width="600" alt="Unbenannt" src="https://user-images.githubusercontent.com/82016318/144563425-c8cafa44-6aee-4d11-9cdb-5409ff07fb6a.PNG">

**Comment by martim01** [comment]
Looks like I'd completely forgotten to add a CMakeLists.txt file to the ptp plugin so it was never being built.
I've now added it and checked that it builds okay and is available as a plugin
