### ISSUE TITLE
Missing  library libwxgtk3.0-dev 

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#67]
I would like to report another bug.
With the current Raspian OS the following package is not found anymore. 

libwxgtk3.0-dev 

It always comes the message, 
Package libwxgtk3.0-dev is not available, but is referenced by another package. This may mean that the package is missing, out of date or only available from another source.

**Comment by martim01** [comment]
looks like the package has been changed to `libwxgtk3.0-gtk3-dev`.
