### ISSUE TITLE
Maybe error in NMOS

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#69]
I found the following when testing NMOS.
On my machine the NMOS port is 8080. 
When I want to access the NMOS API only the x-nmos/ comes up. 
![PAM](https://user-images.githubusercontent.com/82016318/146352112-cc6fb7e3-c3f7-4a59-81f7-b891b6a95002.PNG)
![Unbenannt](https://user-images.githubusercontent.com/82016318/146352116-4a201a14-cae6-4d4e-8184-67fe428b11e6.PNG)

**Comment by martim01** [comment]
I believe this is correct. You can then do
10.120.8.34:8080/x-nmos which should return ["node/","connection/"]
and then you can navigate to 10.120.8.34:8080/x-nmos/node or 10.120.8.34:8080/x-nmos/connection etc.

**Comment by Twister10000** [comment]
You are right if you enter it manually it works fine.

I knew it only that you can click directly on the web page.
Maybe that would be a cool new feature.
