### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by dewiweb** [martim01/pam#7]
I'll try to build pam from source on pi3(raspbian) and linuxmint19 (ubuntu based) and in these two case i've got this error:
[ 91%] Linking CXX executable ../../bin/pam2
CMakeFiles/pam2.dir/pnlNetworkSetup.cpp.o : Dans la fonction « pnlNetworkSetup::ShowConnectionDetails() » :
pnlNetworkSetup.cpp:(.text+0x226) : référence indéfinie vers « NetworkControl::CheckConnection(wxString const&) »
CMakeFiles/pam2.dir/pnlNetworkSetup.cpp.o : Dans la fonction « pnlNetworkSetup::OnlstInterfacesSelected(wxCommandEvent&) » :
pnlNetworkSetup.cpp:(.text+0x89b) : référence indéfinie vers « NetworkControl::CheckConnection(wxString const&) »
collect2: error: ld returned 1 exit status
pam2/CMakeFiles/pam2.dir/build.make:913: recipe for target '../bin/pam2' failed
make[2]: *** [../bin/pam2] Error 1
CMakeFiles/Makefile2:1666: recipe for target 'pam2/CMakeFiles/pam2.dir/all' failed
make[1]: *** [pam2/CMakeFiles/pam2.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by martim01** [comment]
I've updated the code that was causing this error. I've tried using CMake on a raspberry pi and the build now completes.
