### ISSUE TITLE
Crash of the software when calling from the NMOS API

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#74]
Hello 

Happy new year

I found an error today on 05.1.2022. 
The software installs without any problems with NMOS. 
However, as soon as you want to access the API via a browser, the whole software crashes.  I get the following error in the console: 

terminate called after throwing an instance of 'Json::LogicError'.
  what(): in Json::Value::append: requires arrayValue

Thank you for looking at it.

**Comment by martim01** [comment]
Hi,
This was a mistake in the Restgoose library where I was erroneously making a Json::Value an object then treating it as an array. Hence the LogicError. I've fixed the bug and pushed the changes.
