### ISSUE TITLE
Error while saving the network settings

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#76]
I have the following error. 
When saving network settings, PAM does not overwrite the dhcpc.conf correctly. PAM writes everything on one line.

I have attached a screenshot
![Capture_LI](https://user-images.githubusercontent.com/82016318/148756516-3d7b7743-37fd-48d7-b887-b941f0a14970.jpg)

**Comment by martim01** [comment]
Agreed - I was stripping off the "\n" by mistake on reading in the file. Now makes sure that they are added back in again.
I also noticed another bug whilst fixing this that once you'd chosen Static you couldn't go back to DHCP. This is also fixed
