### ISSUE TITLE
No sync from Pi clock

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#82]
Hello

I have been able to find an error regarding the synchronization of the time.

The PAM does not synchronize the time from PTP with the system time.

**Comment by martim01** [comment]
I found an issue with the ptpmonkey library where it wasn't decoding the delay messages it sent correctly. This had worked before but maybe I'd made an assumption that relied on something else that changed. Either way I've fixed that issue.
When I run  the PAM now it looks to me as if it is syncing the system time with PTP.

**Comment by Twister10000** [comment]
Thanks it works now :)
