### ISSUE TITLE
Error message when starting PAM

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#83]
Hello 

I am reporting again with a new error.

When starting PAM I always get this error message. 

I have attached a picture of the error message
![Error](https://user-images.githubusercontent.com/82016318/151136659-90956494-d304-4d21-9d2f-7bdf09a3609c.jpg)

**Comment by martim01** [comment]
Hi,
I've seen this before - it usually means that one of the libraries that the PAM uses can be found in more than one directory of the path.
Between version 1.2 and 1.3 (I think) I changed the location of the libpam*.so libraries from /usr/local/lib/pam2 to /usr/local/lib

If you've built and installed the later version then it's worth checking that the following
### /usr/local/lib
Has the following libraries
* libnmos_base.so
* libnmos_client.so
* libnmos_node.so
* libpambase.so
* libpamfft.so
* libpamlevel.so
* libpml_dnssd.so
* libpml_log.so
* libptpmonkey.so
* librestgoose.so
* libsapserver.so
### /usr/local/lib/pam2
Has no libraries but 3 directories
* generator
* monitor
* test


If any libraries are in /usr/local/pam2 then try deleting them and restarting.
If this doesn't fix the issue then could you press the "Backtrace" button on the error message and post a screen shot of the result.
Thanks

Matt

**Comment by Twister10000** [comment]
Hello

I have checked the directories and everything is now as it should be. 

But now I still get an error message.
I have attached them as images 
![1](https://user-images.githubusercontent.com/82016318/151200560-41f7ad83-4052-409e-993b-e6372efb6624.jpg)
![2](https://user-images.githubusercontent.com/82016318/151200567-64d207ec-fe4d-43da-844d-542a35f9b4af.jpg)
![3](https://user-images.githubusercontent.com/82016318/151200569-eb3b4c6b-227c-4dc5-b000-9454ddcc71d4.jpg)
![4](https://user-images.githubusercontent.com/82016318/151200576-02f65bdb-f21e-4d07-b938-631d26b1e29f.jpg)
![5](https://user-images.githubusercontent.com/82016318/151200577-50ae0c87-a379-4fce-9e28-3973c3cc7d17.jpg)

**Comment by martim01** [comment]
The first screenshot still makes me think that you have the same library in two places. There was a brief bug with the install process that put some of the test plugins in to the monitor directory. I wonder if that has happened here.
Check /usr/local/lib/pam2/monitor and check there is nothing in there that is also in /usr/local/lib/pam2/test or .../generator. If there is then delete it from the monitor directory

**Comment by Twister10000** [comment]
Hello 
I accidentally deleted a wrong library and could not restore it.
I have therefore rebuilt PAM. With the new build I have no longer this error. 
So I can't tell you if your solution would have solved the problem. What I can say, is that there were indeed certain libraries in both places.

**Comment by Twister10000** [comment]
I was able to free the directories from duplicate libraries. 
The error message has now disappeared. 
Thanks a lot for your support with all my questions.
